// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Level    int32  `gorm:"column:level" json:"level"`
	ParentID int32  `gorm:"column:parent_id" json:"parent_id"`
	Name     string `gorm:"column:name" json:"name"`
	Status   int32  `gorm:"column:status" json:"status"`
	Image    string `gorm:"column:image" json:"image"`
	Num      int32  `gorm:"column:num" json:"num"`
	Sort     int32  `gorm:"column:sort" json:"sort"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
