// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameOrderItem = "order_item"

// OrderItem mapped from table <order_item>
type OrderItem struct {
	OrderNum  string  `gorm:"column:order_num" json:"order_num"`
	ProductID int32   `gorm:"column:product_id" json:"product_id"`
	Quantity  int32   `gorm:"column:quantity" json:"quantity"`
	UnitPrice float64 `gorm:"column:unit_price" json:"unit_price"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
