// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	OrderNum    string    `gorm:"column:order_num;primaryKey" json:"order_num"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UserID      int32     `gorm:"column:user_id" json:"user_id"`
	TotalAmount float64   `gorm:"column:total_amount;comment:总价" json:"total_amount"`   // 总价
	OrderStatus int32     `gorm:"column:order_status;comment:状态" json:"order_status"`   // 状态
	PayStatus   int32     `gorm:"column:pay_status;comment:支付状态" json:"pay_status"`     // 支付状态
	PayMethod   int32     `gorm:"column:pay_method;comment:支付方式" json:"pay_method"`     // 支付方式
	PayAt       time.Time `gorm:"column:pay_at;comment:支付时间" json:"pay_at"`             // 支付时间
	CompletedAt time.Time `gorm:"column:completed_at;comment:完成时间" json:"completed_at"` // 完成时间
	CancelledAt time.Time `gorm:"column:cancelled_at;comment:取消时间" json:"cancelled_at"` // 取消时间
	Note        string    `gorm:"column:note;comment:备注" json:"note"`                   // 备注
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
