// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePermission = "permission"

// Permission 权限表
type Permission struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null;comment:权限名称" json:"name"`                       // 权限名称
	Desc      string    `gorm:"column:desc;not null;comment:描述" json:"desc"`                         // 描述
	Method    string    `gorm:"column:method;not null;comment:接口请求方法" json:"method"`                 // 接口请求方法
	Route     string    `gorm:"column:route;not null;comment:接口路由" json:"route"`                     // 接口路由
	Func      string    `gorm:"column:func;not null;comment:接口方法" json:"func"`                       // 接口方法
	FuncPath  string    `gorm:"column:func_path;not null;comment:接口方法路径" json:"func_path"`           // 接口方法路径
	IsAuth    int32     `gorm:"column:is_auth;not null;default:1;comment:是否鉴权 1是 2否" json:"is_auth"` // 是否鉴权 1是 2否
	Sort      int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                         // 排序
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt int32     `gorm:"column:deleted_at;not null;comment:删除时间戳" json:"deleted_at"` // 删除时间戳
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
