// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameProductTag = "product_tag"

// ProductTag mapped from table <product_tag>
type ProductTag struct {
	ProductID int32 `gorm:"column:product_id;not null" json:"product_id"`
	TagID     int32 `gorm:"column:tag_id;not null" json:"tag_id"`
}

// TableName ProductTag's table name
func (*ProductTag) TableName() string {
	return TableNameProductTag
}
