// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameProductImage = "product_image"

// ProductImage mapped from table <product_image>
type ProductImage struct {
	URL       string `gorm:"column:url" json:"url"`
	ProductID int32  `gorm:"column:product_id" json:"product_id"`
}

// TableName ProductImage's table name
func (*ProductImage) TableName() string {
	return TableNameProductImage
}
