// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ID                int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`       // id
	ShopID            int32   `gorm:"column:shop_id;comment:店铺id" json:"shop_id"`                         // 店铺id
	Status            int32   `gorm:"column:status;comment:状态" json:"status"`                             // 状态
	ProductCategoryID int32   `gorm:"column:product_category_id;comment:分类id" json:"product_category_id"` // 分类id
	SalesAll          string  `gorm:"column:sales_all;comment:全部销量" json:"sales_all"`                     // 全部销量
	Sales24           string  `gorm:"column:sales24" json:"sales24"`
	Platform          string  `gorm:"column:platform;comment:平台" json:"platform"`         // 平台
	Title             string  `gorm:"column:title;comment:标题" json:"title"`               // 标题
	Commission        int32   `gorm:"column:commission;comment:佣金" json:"commission"`     // 佣金
	BottomPrice       float64 `gorm:"column:bottom_price;comment:价格" json:"bottom_price"` // 价格
	TrueSales         int32   `gorm:"column:true_sales" json:"true_sales"`
	CommissionValue   float64 `gorm:"column:commission_value" json:"commission_value"`
	Remaining         int32   `gorm:"column:remaining" json:"remaining"`
	ExperienceScore   float64 `gorm:"column:experience_score;not null;comment:体验分" json:"experience_score"` // 体验分
	IsFake            int32   `gorm:"column:is_fake" json:"is_fake"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
