// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSeckill = "seckill"

// Seckill mapped from table <seckill>
type Seckill struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	ProductID      int32          `gorm:"column:product_id;not null;comment:商品id" json:"product_id"`    // 商品id
	Title          string         `gorm:"column:title;not null;comment:活动名称" json:"title"`              // 活动名称
	Status         int32          `gorm:"column:status;not null;comment:状态: 0禁用; 1正常" json:"status"`    // 状态: 0禁用; 1正常
	Count          int32          `gorm:"column:count;not null;comment:数量" json:"count"`                // 数量
	UnitPrice      float64        `gorm:"column:unit_price;not null;comment:单价" json:"unit_price"`      // 单价
	BeginTime      time.Time      `gorm:"column:begin_time;not null;comment:开始时间" json:"begin_time"`    // 开始时间
	EndTime        time.Time      `gorm:"column:end_time;not null;comment:结束时间" json:"end_time"`        // 结束时间
	AllowUserGrade int32          `gorm:"column:allow_user_grade;not null" json:"allow_user_grade"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Seckill's table name
func (*Seckill) TableName() string {
	return TableNameSeckill
}
