// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
