// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUser = "user"

// User 后台管理用户表
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nickname  string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                     // 昵称
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                    // 用户名
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`                     // 密码
	Mobile    string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                        // 手机号
	Email     string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                           // 邮箱
	Avatar    string    `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                         // 头像
	Status    bool      `gorm:"column:status;not null;default:1;comment:状态 1启用 2禁用" json:"status"`       // 状态 1启用 2禁用
	IsAdmin   bool      `gorm:"column:is_admin;not null;default:1;comment:是否管理员 1是 2不是" json:"is_admin"` // 是否管理员 1是 2不是
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt int32     `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"` // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
